version: 2
jobs:
  build:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/docker_image
    steps:
      - checkout
      - run:
          name: docker build
          no_output_timeout: 60m
          command: |
            for i in {1..5}; do
              docker build -t miykael/nipype_tutorial:$CIRCLE_BRANCH . && break || sleep 15
            done
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/docker_image

  notebooks_basic:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/docker_image
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: run basic notebooks
          no_output_timeout: 90m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_basic.py


  notebooks_introduction:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/docker_image
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: run basic notebooks
          no_output_timeout: 90m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_introduction.py

  notebooks_example:
    docker:
      - image: docker:17.10.0-ce-git
    working_directory: ~/docker_image
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: run example notebooks
          no_output_timeout: 120m
          command: |
            docker run -it --rm miykael/nipype_tutorial:$CIRCLE_BRANCH pytest -v -s /home/neuro/nipype_tutorial/tests/test_notebooks_example.py

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - notebooks_basic:
          requires:
            - build
      - notebooks_introduction:
          requires:
            - build
      - notebooks_example:
          requires:
            - build
